#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services specific to this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pi-webradio
#
# --------------------------------------------------------------------------

# --- defaults used during installation   ----------------------------------

PACKAGES="python3-pip python3-flask mpg123 mp3info"
PACKAGES_PIP="sseclient-py"

PROJECT="pi-webradio"
USERNAME="${1:-pi}"

# --- basic packages   ------------------------------------------------------

if [ -n "$PACKAGES" ]; then
  apt-get update
  apt-get -y install $PACKAGES
fi

# install PIP3 packages
[ -n "$PACKAGES_PIP" ] && pip3 --disable-pip-version-check install $PACKAGES_PIP

# --- install specific files   ----------------------------------------------

rand="$RANDOM"
if [ -f /etc/${PROJECT}.conf ]; then
  # save current configuration
  mv /etc/${PROJECT}.conf /etc/${PROJECT}.conf.$rand
fi

for f in `find $(dirname "$0")/../files/ -type f -not -name "*.pyc"`; do
  target="${f#*files}"
  target_dir="${target%/*}"
  [ ! -d "$target_dir" ] && mkdir -p "$target_dir"
  cp "$f" "$target"
  chown root:root "$target"
done

chmod 755 /usr/local/bin/${PROJECT}.py
chmod 755 /usr/local/bin/webradio_cli.py
chmod 644 /etc/${PROJECT}.conf
chmod 644 /etc/${PROJECT}.channels
chmod 644 /etc/systemd/system/${PROJECT}.service

# restore old configuration
if [ -f /etc/${PROJECT}.conf.$rand ]; then
  mv -f /etc/${PROJECT}.conf /etc/${PROJECT}.conf.new
  mv /etc/${PROJECT}.conf.$rand /etc/${PROJECT}.conf
  echo -e "\nnew version of configuration file: /etc/${PROJECT}.conf.new"
fi

# --- fix user of service   -------------------------------------------------

sed -i -e "/User=/s/=.*/=$USERNAME/" /etc/systemd/system/${PROJECT}.service
usermod -a -G audio "$USERNAME"

# --- activate service   ----------------------------------------------------

#systemctl enable ${PROJECT}.service

# --- final configuration is manual   ---------------------------------------

echo -e "\nPlease edit /etc/${PROJECT}.conf and start ${PROJECT}.service"
